import drizzle from "../assets/images/icon-drizzle.webp";
import fog from "../assets/images/icon-fog.webp";
import overcast from "../assets/images/icon-overcast.webp";
import partlyCloudy from "../assets/images/icon-partly-cloudy.webp";
import rain from "../assets/images/icon-rain.webp";
import snow from "../assets/images/icon-snow.webp";
import sunny from "../assets/images/icon-sunny.webp";

const useData = () => {
  const weatherIcons = {
    0: sunny,
    1: partlyCloudy,
    2: partlyCloudy,
    3: overcast,
    45: fog,
    48: fog,
    51: drizzle,
    53: drizzle,
    55: drizzle,
    61: rain,
    63: rain,
    65: rain,
    71: snow,
    73: snow,
    75: snow,
    77: snow,
    80: rain,
    81: rain,
    82: rain,
    85: snow,
    86: snow,
  };

  const iconsAlt = {
    0: "sunny",
    1: "partly cloudy",
    2: "partly cloudy",
    3: "overcast",
    45: "fog",
    48: "fog",
    51: "drizzle",
    53: "drizzle",
    55: "drizzle",
    61: "rain",
    63: "rain",
    65: "rain",
    71: "snow",
    73: "snow",
    75: "snow",
    77: "snow",
    80: "rain",
    81: "rain",
    82: "rain",
    85: "snow",
    86: "snow",
  };

  const citiesData = [
    "Tokyo",
    "Delhi",
    "Shanghai",
    "São Paulo",
    "Mexico City",
    "Cairo",
    "Mumbai",
    "Beijing",
    "Dhaka",
    "Osaka",
    "New York City",
    "Karachi",
    "Buenos Aires",
    "Chongqing",
    "Istanbul",
    "Kolkata",
    "Manila",
    "Lagos",
    "Rio de Janeiro",
    "Tianjin",
    "Kinshasa",
    "Guangzhou",
    "Los Angeles",
    "Moscow",
    "Shenzhen",
    "Lahore",
    "Bangalore",
    "Paris",
    "Bogotá",
    "Jakarta",
    "Chennai",
    "Lima",
    "Bangkok",
    "Seoul",
    "Nagoya",
    "Hyderabad",
    "London",
    "Tehran",
    "Chicago",
    "Chengdu",
    "Nanjing",
    "Wuhan",
    "Ho Chi Minh City",
    "Luanda",
    "Ahmedabad",
    "Kuala Lumpur",
    "Hong Kong",
    "Baghdad",
    "Riyadh",
    "Santiago",
    "Madrid",
    "Toronto",
    "Dallas",
    "Houston",
    "Miami",
    "Philadelphia",
    "Atlanta",
    "Boston",
    "San Francisco",
    "Washington, D.C.",
    "Seattle",
    "Barcelona",
    "Berlin",
    "Rome",
    "Milan",
    "Munich",
    "Frankfurt",
    "Sydney",
    "Melbourne",
    "Perth",
    "Brisbane",
    "Auckland",
    "Cape Town",
    "Johannesburg",
    "Durban",
    "Casablanca",
    "Algiers",
    "Addis Ababa",
    "Nairobi",
    "Accra",
    "Abuja",
    "Doha",
    "Dubai",
    "Abu Dhabi",
    "Tel Aviv",
    "Jerusalem",
    "Amman",
    "Damascus",
    "Beirut",
    "Kuwait City",
    "Muscat",
    "Islamabad",
    "Kathmandu",
    "Hanoi",
    "Yangon",
    "Phnom Penh",
    "Vientiane",
    "Singapore",
    "Stockholm",
    "Oslo",
    "Copenhagen",
    "Helsinki",
    "Reykjavik",
    "Warsaw",
    "Krakow",
    "Budapest",
    "Prague",
    "Vienna",
    "Bratislava",
    "Belgrade",
    "Sofia",
    "Bucharest",
    "Athens",
    "Thessaloniki",
    "Skopje",
    "Sarajevo",
    "Zagreb",
    "Ljubljana",
    "Podgorica",
    "Tirana",
    "Vilnius",
    "Riga",
    "Tallinn",
    "Minsk",
    "Kiev",
    "Odessa",
    "Kharkiv",
    "Dnipro",
    "Lviv",
    "Saint Petersburg",
    "Novosibirsk",
    "Yekaterinburg",
    "Kazan",
    "Samara",
    "Rostov-on-Don",
    "Ufa",
    "Chelyabinsk",
    "Omsk",
    "Perm",
    "Volgograd",
    "Baku",
    "Tbilisi",
    "Yerevan",
    "Astana",
    "Almaty",
    "Bishkek",
    "Tashkent",
    "Samarkand",
    "Dushanbe",
    "Ashgabat",
    "Ulaanbaatar",
    "Havana",
    "Santo Domingo",
    "Port-au-Prince",
    "San Juan",
    "Kingston",
    "Havana",
    "Panama City",
    "San José",
    "Managua",
    "Tegucigalpa",
    "San Salvador",
    "Guatemala City",
    "Belmopan",
    "Port of Spain",
    "Georgetown",
    "Paramaribo",
    "Brasília",
    "Fortaleza",
    "Salvador",
    "Recife",
    "Curitiba",
    "Belo Horizonte",
    "Porto Alegre",
    "Manaus",
    "Brasília",
    "Quito",
    "Guayaquil",
    "La Paz",
    "Santa Cruz de la Sierra",
    "Cochabamba",
    "Asunción",
    "Montevideo",
    "Caracas",
    "Maracaibo",
    "Valencia",
    "Barranquilla",
    "Cali",
    "Medellín",
    "Cartagena",
    "Cusco",
    "Arequipa",
    "Trujillo",
    "Lusaka",
    "Harare",
    "Bulawayo",
    "Gaborone",
    "Windhoek",
    "Maputo",
    "Antananarivo",
    "Port Louis",
    "Victoria",
    "Moroni",
    "Saint-Denis",
    "Dar es Salaam",
    "Dodoma",
    "Mombasa",
    "Kigali",
    "Bujumbura",
    "Kinshasa",
    "Lubumbashi",
    "Mbandaka",
    "Brazzaville",
    "Libreville",
    "Malabo",
    "Yaoundé",
    "Douala",
    "Bamako",
    "Dakar",
    "Banjul",
    "Nouakchott",
    "Conakry",
    "Freetown",
    "Monrovia",
    "Ouagadougou",
    "Niamey",
    "Lomé",
    "Cotonou",
    "Porto-Novo",
    "Abidjan",
    "Yamoussoukro",
    "Bissau",
    "Praia",
  ];

  return {
    citiesData,
    weatherIcons,
    iconsAlt,
  };
};

export default useData;
